#!/bin/bash
# Autogenerated test for color-tools feature
set -e

echo "Testing color-tools feature..."

# Check that the config file was created
if [ ! -f /usr/local/etc/color-config.conf ]; then
    echo "ERROR: color-config.conf not found"
    exit 1
fi

# Check that FAVORITE_COLOR is set
if [ -z "$FAVORITE_COLOR" ]; then
    echo "ERROR: FAVORITE_COLOR environment variable not set"
    exit 1
fi

# Verify the config file contains color setting
if ! grep -q "FAVORITE_COLOR" /usr/local/etc/color-config.conf; then
    echo "ERROR: Color configuration not found in config file"
    exit 1
fi

echo "✓ All checks passed for color-tools feature"
exit 0
