# syntax=docker/dockerfile:1
#  Copyright (c) Microsoft Corporation. All rights reserved.
#  Licensed under the MIT License. See License.txt in the project root for license information.
ARG VARIANT="bookworm-slim"
FROM debian:${VARIANT}

LABEL syntax_directive_probe="success"
