//! Error types for features test operations.
//!
//! This module defines the [`enum@Error`] type which represents all possible errors that can
//! occur during test discovery and execution.

use thiserror::Error;

/// Errors that can occur during features test operations.
///
/// This enum covers errors from test discovery (parsing, missing files) through
/// execution (runtime issues, I/O failures).
#[derive(Error, Debug)]
pub enum Error {
    /// Invalid combination of command-line flags.
    ///
    /// For example, using `--skip-scenarios` and `--skip-autogenerated` together
    /// would leave no tests to run.
    #[error("Invalid flag combination: {0}")]
    InvalidFlags(String),

    /// Test collection directory not found at the specified path.
    #[error("Collection not found: {0}")]
    CollectionNotFound(String),

    /// Required subdirectory (src/ or test/) is missing from the collection.
    #[error("Missing required directory: {0}")]
    MissingDirectory(String),

    /// Expected test script (test.sh, install.sh, or scenario script) does not exist.
    #[error("Missing test script: {0}")]
    MissingTestScript(String),

    /// Failed to parse a scenarios.json or scenarios.jsonc file.
    ///
    /// This can occur if the file contains invalid JSON/JSONC, is not an array,
    /// or scenario objects are missing required fields.
    #[error("Scenario parse error: {0}")]
    ScenarioParse(String),

    /// Docker or another required runtime is unavailable or failed.
    ///
    /// This includes failures to create containers, execute commands, or communicate
    /// with the Docker daemon.
    #[error("Runtime unavailable: {0}")]
    RuntimeUnavailable(String),

    /// I/O error reading or writing files.
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),

    /// JSON serialization or deserialization error.
    #[error("JSON error: {0}")]
    Json(#[from] serde_json::Error),

    /// Other unclassified errors.
    #[error("Other error: {0}")]
    Other(String),
}
