//! Feature testing infrastructure for dev container features.
//!
//! This module provides functionality for discovering and executing tests for dev container
//! features. It supports multiple test types including autogenerated tests, duplicate/idempotence
//! tests, and custom scenario tests.
//!
//! # Test Collection Structure
//!
//! A test collection is organized as:
//! ```text
//! collection-root/
//!   src/
//!     feature-a/
//!       devcontainer-feature.json
//!       install.sh
//!     feature-b/
//!       ...
//!   test/
//!     feature-a/
//!       test.sh              (autogenerated test)
//!       scenarios.json       (scenario definitions)
//!       scenario-1.sh
//!       scenario-2.sh
//!     feature-b/
//!       ...
//!     _global/
//!       scenarios.json       (global scenarios)
//!       scenario-x.sh
//! ```
//!
//! # Module Organization
//!
//! - [`model`] - Data types representing test collections, features, scenarios, and results
//! - [`discovery`] - Functions for discovering test collections, features, and scenarios
//! - [`runner`] - Functions for executing tests in Docker containers
//! - [`errors`] - Error types for features test operations

pub mod discovery;
pub mod errors;
pub mod model;
pub mod runner;
