#!/bin/bash
# Autogenerated test for hello-world feature
set -e

echo "Testing hello-world feature..."

# Check that the message file was created
if [ ! -f /usr/local/hello-message.txt ]; then
    echo "ERROR: hello-message.txt not found"
    exit 1
fi

# Check that the message contains expected content
if ! grep -q "World" /usr/local/hello-message.txt; then
    echo "ERROR: Expected greeting not found in message file"
    exit 1
fi

# Check environment variable is set
if [ -z "$HELLO_MESSAGE" ]; then
    echo "ERROR: HELLO_MESSAGE environment variable not set"
    exit 1
fi

echo "✓ All checks passed for hello-world feature"
exit 0
