name: maverick-intake-poller

# Polls for items in the "Ready for Takeoff" status and moves them to "In Flight".
# Creates a Copilot agent task and (optionally) posts a kickoff comment.

on:
  # Scheduled polling interval. Adjust the cron as needed.
  # schedule:
  #   - cron: "*/5 * * * *"
  # Allow manual dispatch to run on demand.
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  # Organization and project configuration. Update these values to your org and project.
  ORG: get2knowio
  PROJECT_NUMBER: "1"
  # Status option names. These should match the names (including emoji) of your project Status field.
  STATUS_READY: "Ready for Takeoff"
  STATUS_INFLIGHT: "In Flight"
  # Comment posted to kick off Copilot work. Customize as needed.
  COPILOT_KICKOFF: "@copilot please start working on this issue"

jobs:
  intake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run intake poller
        env:
          GH_PAT: ${{ secrets.ORG_PROJECTS_TOKEN }}
          ORG: ${{ env.ORG }}
          PROJECT_NUMBER: ${{ env.PROJECT_NUMBER }}
          STATUS_READY: ${{ env.STATUS_READY }}
          STATUS_INFLIGHT: ${{ env.STATUS_INFLIGHT }}
          COPILOT_KICKOFF: ${{ env.COPILOT_KICKOFF }}
        run: |
          # Verify token is available
          if [ -z "$GH_PAT" ]; then
            echo "ERROR: ORG_PROJECTS_TOKEN secret is not set"
            echo "This workflow requires a Personal Access Token (classic) with the following scopes:"
            echo "  - repo (full control)"
            echo "  - read:org, write:org (for Projects v2)"
            echo "  - user (for agent-task creation)"
            exit 1
          fi
          
          # Unset GH_TOKEN temporarily so gh auth login can work
          unset GH_TOKEN
          
          # Configure gh CLI to use the PAT for authentication
          # This is required for gh agent-task which needs OAuth-style auth
          echo "$GH_PAT" | gh auth login --with-token
          
          # Now run the poller with GH_TOKEN set for the script
          export GH_TOKEN="$GH_PAT"
          python .github/workflow-scripts/maverick/intake_poller.py
